
"""Add medical_center table

Revision ID: 45b6f8a28b5b
Revises: fe56fa70289e
Create Date: 2024-07-29 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '45b6f8a28b5b'
down_revision = 'fe56fa70289e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medicalcenter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('address', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('city', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('specialty', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('working_hours', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('emergency_available', sa.Boolean(), nullable=False),
    sa.Column('approximate_price_level', sa.Integer(), nullable=True),
    sa.Column('yandex_uri', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medicalcenter_city'), 'medicalcenter', ['city'], unique=False)
    op.create_index(op.f('ix_medicalcenter_name'), 'medicalcenter', ['name'], unique=False)
    op.create_index(op.f('ix_medicalcenter_specialty'), 'medicalcenter', ['specialty'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_medicalcenter_specialty'), table_name='medicalcenter')
    op.drop_index(op.f('ix_medicalcenter_name'), table_name='medicalcenter')
    op.drop_index(op.f('ix_medicalcenter_city'), table_name='medicalcenter')
    op.drop_table('medicalcenter')
    # ### end Alembic commands ###
